### ISSUE TITLE
dotnet on ARM32 and ARM64

### ISSUE THREAD

**Issue by johnwason** [conda-forge/dotnet-feedstock#27]
The dotnet conda-forge packages do not currently support ARM32 and ARM64. Binaries are available from Microsoft to support these architectures. It would be helpful to IoT applications if these architectures were included in conda-forge.

**Comment by acesnik** [comment]
There's `osx_arm64` for macOS with ARM64 and `aarch64` for Linux with ARM64, but I haven't come across any such tags for Windows with ARM64 or ARM32. Does anyone know what they are or if they exist?

**Comment by acesnik** [comment]
The Linux ones should be fairly easy to package. 👍🏼

**Comment by johnwason** [comment]
Oh sorry I was referring to ARM64 Linux, which would be aarch64. Having the armhf package would also be helpful, although I guess conda-forge doesn't officially support it.

The Windows ARM64 is here: https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.202-windows-arm64-installer

I don't have an ARM64 Windows device so I can't test it.

**Comment by acesnik** [comment]
I gave it a shot in those PRs. I skipped the `lttng-ust` dependency for aarch64, which I don't know if appropriate, but it does look like `dotnet` gives signs of life without it. If that doesn't work, we may need to find a way to get the `lttng-ust` packaged for aarch64.

**Comment by acesnik** [comment]
Merged those two PRs but let us know if you run into trouble regarding `lttng-ust`. I don't have an ARM64 Linux machine to test it out.

**Comment by johnwason** [comment]
I will try it on a raspi 4 today.

**Comment by johnwason** [comment]
I tested some basic programs on a raspi 4 and they seem to work fine. I'll let you know if I run in to any errors in the future.
