### ISSUE TITLE
dotnet interactive

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/dotnet-feedstock#7]
It would be cool to have https://github.com/dotnet/interactive `conda` installable!

```
dotnet tool install --tool-path $env:DOTNET_TOOLS --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
```

**Comment by dhirschfeld** [comment]
Need to put the `tools` folder on the `PATH`:


![image](https://user-images.githubusercontent.com/881019/99027562-431bb980-25b9-11eb-8623-f50255fb90be.png)


https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-global-tool-in-a-custom-location

**Comment by dhirschfeld** [comment]
Not yet working with .NET5 - https://github.com/dotnet/interactive/issues/869

**Comment by dhirschfeld** [comment]
Resolved by https://github.com/conda-forge/staged-recipes/pull/13328

**Comment by acesnik** [comment]
https://github.com/conda-forge/staged-recipes/pull/13328
https://github.com/conda-forge/dotnet-interactive-feedstock
